scss_files: 'src/assets/style/**/*.scss'

linters:
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  BorderZero:
    convention: none
  FinalNewline:
    enabled: false
  IdSelector:
    enabled: false
  SelectorDepth:
    enabled: false
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
