version: "2"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
    - '5432:5432'
    restart: unless-stopped
    volumes:
    - postgres:/data/postgres

  backend:
    build: backend
    environment:
      POSTGRES_HOST: postgres
#      POSTGRES_PORT: 5432
#      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: 'postgres'
    ports:
    - '5000:5000'
    restart: unless-stopped
    depends_on:
      - postgres
    expose:
      - 5000

  frontend:
    build: frontend
    ports:
    - "81:80"
    environment:
      API_HOST: backend
      API_PORT: 5000
    restart: unless-stopped
    depends_on:
    - backend
    links:
    - backend

volumes:
  postgres:

